### ISSUE TITLE
Use for-await

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/get-stdin#25]
When it's in a Node.js version we can target: https://github.com/nodejs/node/commit/61b4d60c5d9694e79069b1680b3736c96a5de501

**Comment by Gasol** [comment]
This feature is very useful when deal with large stdin stream, The Async Iterator is experimental and available since Node 10 in https://github.com/nodejs/node/pull/17755, and also mark as stable on [Node 12](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_consuming_readable_streams_with_async_iterators).

**Comment by Richienb** [comment]
Node 10 is now in LTS. Time to implement!
